### PR TITLE
Looks to fix issue #10 EVALSYS-1578

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by jonespm** [comment]
If someone has a better fix I'm all for it! The fix to StandardDynamicListInputEvolver.java I'm pretty confident in, but the one to GeneralLeafParser is when saving the form back. It seems to work fine and be able to parse this with that class. I'm not 100% sure how it was able to parse String[] before since the explicit parse for that in GeneralLeafParser was commented out years ago but maybe there's something else I'm missing here. 

`      //registerParser(ArrayUtil.stringArrayClass, StringArrayParser.instance);
`

We could create a custom Parser for List but it really doesn't *seem* to be necessary.

**Review by ottenhoff — APPROVED** [review]
Looks good to me. Thanks Matt. @ern?

**Comment by ottenhoff** [comment]
@ern?

**Comment by ottenhoff** [comment]
Do we need to release a new RSF after this merge?

Also looks like test error after this merge:

uk.org.ponder.util.UniversalRuntimeException: 
Error writing object of class class uk.org.ponder.rsf.view.ViewRoot
--> Error writing object for view
--> Error while writing tag component
--> uk.org.ponder.rsf.components.ComponentList cannot be cast to java.lang.String
	at uk.org.ponder.rsf.test.flow.TestFlowLoader.testLoadFlow(TestFlowLoader.java:20)

**Comment by jonespm** [comment]
I don't really remember much of this change now. I feel like it might not be correct and I guess I didn't run this test? 

There were these 4 "historical" parsers in here that were disabled, int/double/string arrays and matrix. 

I think I tried to do a "quick hack" to handle the `List.class ` but the render method for a ComponentList isn't correct here.

I'm inclined to believe the code is wrong at
`    registerParser(List.class, new StringParser());`

rather than the test. I feel like I tried to use the historical parsers that were there but those looked like they had a lot of issues with them. 

I also don't know why these historical parsers were removed back in 2008 in 832c763d732e948089c7951e8adf23c01d055c2e

This is going to need some more work.

**Comment by jonespm** [comment]
I *only* really tested this on Evaluation and this was never QA'd in regular Sakai so I probably wouldn't release in 20 without switching it and doing more testing especially with this test failure. I created a new issue for that.

**Comment by ern** [comment]
This issue was solved in https://github.com/sakaicontrib/evaluation/pull/147, Matt you okay with reverting this change?

**Comment by jonespm** [comment]
@ern #12

**Comment by amb26** [comment]
Gosh, guys - I really had no idea this stuff was going on so long after. You are all superheroes for threading your way through this maze.
I ask for forgiveness in plaguing future generations with this code - I thought I was doing good at the time, is my only defence - but what kind of defence is that : P
Hats off to all of you for keeping Sakai distributions running and viable 12 years later.

**Comment by jonespm** [comment]
Hi @amb26 and nice to hear from you! This is a maze and it is still actively in use! On the roadmap we've got plans to replace the tools that are still using RSF but it's a multi-year effort. Many of the core tools still are using RSF.

Luckily this library hasn't really needed many major changes (yet) and we've been able to work around most of them without changing the code. The concern is that it might eventually need large changes, any changes have regression potential, and it things could be done to increase stability.

Like this change solved one problem but caused another so it was incomplete and was reverted and fixed another way. :/

**Pull request merged**
